spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexters
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expires-in: 86400000
  refresh-token:
    expires-in: 1209600000

springdoc:
  swagger-ui:
    path: /missionmate-docs.html
    query-config-enabled: true
    enabled: true

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ${OAUTH_APPLE_CLIENT_ID}