spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    user: sa
    baseline-version: 0

jwt:
  secret: ${JWT_SECRET}
  access-token:
    expires-in: 86400000
  refresh-token:
    expires-in: 1209600000

springdoc:
  swagger-ui:
    path: /missionmate-docs.html
    query-config-enabled: true
    enabled: true

oauth:
  apple:
    iss: https://appleid.apple.com
    client-id: ${OAUTH_APPLE_CLIENT_ID}