spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop

oauth:
  apple:
    grant-type: authorization_code
    iss: https://appleid.apple.com
    client-id: ${OAUTH_APPLE_CLIENT_ID}
    nonce: nonce
    key-id: ${OAUTH_APPLE_KEY_ID}
    team-id: ${OAUTH_APPLE_TEAM_ID}
    private-key: ${OAUTH_APPLE_PRIVATE_KEY}