name: Backend CI

on:
  pull_request:
    branches:
      - main
      - develop

    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: action checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build